DO $$ BEGIN CREATE TYPE user_role AS ENUM ('ADMIN', 'USER', 'OWNER'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(60) NOT NULL, email VARCHAR(254) UNIQUE NOT NULL,
  address VARCHAR(400) NOT NULL DEFAULT '', password_hash TEXT NOT NULL, role user_role NOT NULL DEFAULT 'USER',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS stores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(120) NOT NULL, email VARCHAR(254) UNIQUE NOT NULL,
  address VARCHAR(400) NOT NULL, owner_id UUID UNIQUE REFERENCES users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS ratings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), store_id UUID NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(store_id, user_id)
);
CREATE INDEX IF NOT EXISTS stores_name_idx ON stores(name); CREATE INDEX IF NOT EXISTS users_email_idx ON users(email); CREATE INDEX IF NOT EXISTS ratings_store_idx ON ratings(store_id);
